// Chinese configuration taxonomy derived from the original NiceGUI webui.py in AI-Vtuber-20250604.tar.
import { PLATFORM_CATALOG } from "../src/platforms/availability.js";


export interface SettingsCatalogSection {
  readonly id: string;
  readonly label: string;
  readonly keys: readonly string[];
}

export interface SettingsCatalogCategory {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly sections: readonly SettingsCatalogSection[];
}

export type SettingsCatalogSectionGroup = SettingsCatalogSection;

export interface SettingsCatalogCategoryGroup {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly sections: readonly SettingsCatalogSectionGroup[];
}

export interface SettingsChoiceOption {
  readonly value: string;
  readonly label: string;
  readonly disabled?: boolean;
}

const AUDIO_SYNTHESIS_OPTIONS = [
  { value: "none", label: "不启用" },
  { value: "edge-tts", label: "Edge TTS" },
  { value: "azure_tts", label: "Azure TTS" },
  { value: "openai_tts", label: "OpenAI TTS" },
  { value: "vits", label: "VITS" },
  { value: "bert_vits2", label: "Bert-VITS2" },
  { value: "gpt_sovits", label: "GPT-SoVITS" },
] as const;

const LANGUAGE_OPTIONS = [
  { value: "自动识别", label: "自动识别" },
  { value: "中文", label: "中文" },
  { value: "日文", label: "日文" },
  { value: "英文", label: "英文" },
] as const;

const SENTENCE_SPLIT_OPTIONS = [
  { value: "不切", label: "不切" },
  { value: "凑四句一切", label: "每四句切分" },
  { value: "凑50字一切", label: "每 50 字切分" },
  { value: "按中文句号。切", label: "按中文句号切分" },
  { value: "按英文句号.切", label: "按英文句号切分" },
  { value: "按标点符号切", label: "按标点符号切分" },
] as const;

const SETTINGS_PATH_OPTIONS: Readonly<
  Record<string, readonly SettingsChoiceOption[]>
> = {
  "[\"platform\"]": PLATFORM_CATALOG.map(({ id, label, status }) => ({
    value: id,
    label: `${label}（${id}）${status === "pending" ? " · 待完善" : ""}`,
    disabled: status === "pending",
  })),
  "[\"comment_log_type\"]": [
    { value: "问答", label: "记录问题与回答" },
    { value: "问题", label: "仅记录问题" },
    { value: "回答", label: "仅记录回答" },
    { value: "不记录", label: "不记录" },
  ],
  "[\"visual_body\"]": [
    { value: "其他", label: "其他（外置）" },
    { value: "live2d", label: "内置 Live2D" },
    { value: "EasyAIVtuber", label: "EasyAIVtuber" },
  ],
  "[\"audio_synthesis_type\"]": AUDIO_SYNTHESIS_OPTIONS,
  "[\"play_audio\",\"player\"]": [
    { value: "pygame", label: "兼容模式（pygame 配置值）" },
    { value: "ffplay", label: "FFplay" },
    { value: "audio_player_v2", label: "Audio Player v2" },
    { value: "audio_player", label: "Audio Player" },
  ],
  "[\"search_online\",\"provider\"]": [
    { value: "tavily", label: "Tavily" },
    { value: "exa", label: "Exa" },
    { value: "openai", label: "OpenAI" },
    { value: "zai", label: "Z.ai" },
    { value: "kimi", label: "Kimi" },
  ],
  "[\"idle_time_task\",\"type\"]": [
    { value: "待合成消息队列更新闲时", label: "待合成消息队列更新闲时" },
    { value: "待播放音频队列更新闲时", label: "待播放音频队列更新闲时" },
    { value: "直播间无消息更新闲时", label: "直播间无消息更新闲时" },
  ],
  "[\"vits\",\"type\"]": [
    { value: "vits", label: "VITS" },
    { value: "bert_vits2", label: "Bert-VITS2" },
  ],
  "[\"vits\",\"lang\"]": [
    { value: "自动", label: "自动" },
    { value: "中文", label: "中文" },
    { value: "英文", label: "英文" },
    { value: "日文", label: "日文" },
  ],
  "[\"bert_vits2\",\"type\"]": [
    { value: "hiyori", label: "Hiyori API" },
  ],
  "[\"bert_vits2\",\"language\"]": [
    { value: "auto", label: "自动" },
    { value: "ZH", label: "中文" },
    { value: "JP", label: "日文" },
    { value: "EN", label: "英文" },
  ],
  "[\"openai_tts\",\"type\"]": [
    { value: "api", label: "API" },
  ],
  "[\"openai_tts\",\"model\"]": [
    { value: "tts-1", label: "tts-1" },
    { value: "tts-1-hd", label: "tts-1-hd" },
  ],
  "[\"openai_tts\",\"voice\"]": [
    { value: "alloy", label: "alloy" },
    { value: "echo", label: "echo" },
    { value: "fable", label: "fable" },
    { value: "onyx", label: "onyx" },
    { value: "nova", label: "nova" },
    { value: "shimmer", label: "shimmer" },
  ],
  "[\"gpt_sovits\",\"type\"]": [
    { value: "api", label: "API" },
    { value: "api_0322", label: "API 0322" },
    { value: "gradio_0322", label: "Gradio 0322" },
    { value: "api_0706", label: "API 0706" },
    { value: "v2_api_0821", label: "V2 API 0821" },
    { value: "webtts", label: "WebTTS" },
  ],
  "[\"gpt_sovits\",\"prompt_language\"]": LANGUAGE_OPTIONS.slice(1),
  "[\"gpt_sovits\",\"language\"]": LANGUAGE_OPTIONS,
  "[\"gpt_sovits\",\"cut\"]": SENTENCE_SPLIT_OPTIONS,
  "[\"gpt_sovits\",\"api_0322\",\"prompt_lang\"]": LANGUAGE_OPTIONS.slice(1),
  "[\"gpt_sovits\",\"api_0322\",\"text_lang\"]": [
    ...LANGUAGE_OPTIONS,
    { value: "中英混合", label: "中英混合" },
    { value: "日英混合", label: "日英混合" },
    { value: "多语种混合", label: "多语种混合" },
  ],
  "[\"gpt_sovits\",\"api_0322\",\"text_split_method\"]": SENTENCE_SPLIT_OPTIONS,
  "[\"gpt_sovits\",\"api_0706\",\"prompt_language\"]": LANGUAGE_OPTIONS.slice(1),
  "[\"gpt_sovits\",\"api_0706\",\"text_language\"]": [
    ...LANGUAGE_OPTIONS,
    { value: "中英混合", label: "中英混合" },
    { value: "日英混合", label: "日英混合" },
    { value: "多语种混合", label: "多语种混合" },
  ],
  "[\"gpt_sovits\",\"v2_api_0821\",\"prompt_lang\"]": [
    { value: "zh", label: "中文" },
    { value: "ja", label: "日文" },
    { value: "en", label: "英文" },
  ],
  "[\"gpt_sovits\",\"v2_api_0821\",\"text_lang\"]": [
    { value: "all_zh", label: "中文" },
    { value: "all_yue", label: "粤语" },
    { value: "en", label: "英文" },
    { value: "all_ja", label: "日文" },
    { value: "all_ko", label: "韩文" },
    { value: "zh", label: "中英混合" },
    { value: "yue", label: "粤英混合" },
    { value: "ja", label: "日英混合" },
    { value: "ko", label: "韩英混合" },
    { value: "auto", label: "多语种混合" },
    { value: "auto_yue", label: "多语种混合（粤语）" },
  ],
  "[\"gpt_sovits\",\"v2_api_0821\",\"text_split_method\"]": [
    { value: "cut0", label: "不切" },
    { value: "cut1", label: "每四句切分" },
    { value: "cut2", label: "每 50 字切分" },
    { value: "cut3", label: "按中文句号切分" },
    { value: "cut4", label: "按英文句号切分" },
    { value: "cut5", label: "按标点符号切分" },
  ],
  "[\"gpt_sovits\",\"webtts\",\"version\"]": [
    { value: "1", label: "1" },
    { value: "1.4", label: "1.4" },
    { value: "2", label: "2" },
  ],
  "[\"gpt_sovits\",\"webtts\",\"lang\"]": [
    { value: "zh", label: "中文" },
    { value: "en", label: "英文" },
    { value: "jp", label: "日文" },
  ],
  "[\"webui\",\"log\",\"log_level\"]": [
    { value: "DEBUG", label: "DEBUG" },
    { value: "INFO", label: "INFO" },
    { value: "WARNING", label: "WARNING" },
    { value: "ERROR", label: "ERROR" },
    { value: "CRITICAL", label: "CRITICAL" },
  ],
};

export const SETTINGS_CATALOG: readonly SettingsCatalogCategory[] = [
  {
    id: "agent",
    label: "Pi Agent / 大语言模型",
    description: "主模型负责对话与可用的图片输入；主模型不支持视觉时可启用独立的 Pi 视觉转述模型。",
    sections: [
      { id: "pi-agent", label: "Pi Agent 主配置与视觉转述", keys: ["agent", "image_recognition"] },
    ],
  },
  {
    id: "common",
    label: "通用配置",
    description: "直播平台、回复流程、过滤、播放与自动化等原 WebUI 通用设置。",
    sections: [
      { id: "core", label: "基础运行", keys: ["api_ip","api_port","platform","room_display_id","before_prompt","after_prompt","comment_template","reply_template","comment_log_type","audio_synthesis_type","visual_body","header"] },
      { id: "platforms", label: "平台相关", keys: ["bilibili-web","bilibili-platform","youtube","ordinaryroad_barrage_fly","twitch"] },
      { id: "audio-playback", label: "音频播放", keys: ["play_audio","virtual_microphone","speech"] },
      { id: "filter", label: "关键词屏蔽", keys: ["filter"] },
      { id: "thanks", label: "LLM 答谢", keys: ["thanks"] },
      { id: "schedule", label: "定时任务", keys: ["schedule"] },
      { id: "idle", label: "闲时任务", keys: ["idle_time_task"] },
      { id: "search", label: "联网搜索", keys: ["search_online"] },
      { id: "captions", label: "日志与字幕", keys: ["captions"] },
      { id: "database", label: "数据库", keys: ["database"] },
    ],
  },
  {
    id: "tts",
    label: "文本转语音",
    description: "原 WebUI“文本转语音”页中的语音服务与合成参数。",
    sections: [
      { id: "edge", label: "Edge TTS", keys: ["edge-tts"] },
      { id: "vits", label: "VITS Simple API", keys: ["vits"] },
      { id: "bert-vits", label: "Bert-VITS2", keys: ["bert_vits2"] },
      { id: "openai-tts", label: "OpenAI TTS", keys: ["openai_tts"] },
      { id: "sovits", label: "GPT-SoVITS", keys: ["gpt_sovits"] },
      { id: "azure", label: "Azure TTS", keys: ["azure_tts"] },
    ],
  },
  {
    id: "svc",
    label: "变声",
    description: "原 WebUI“变声”页中的声音转换服务。",
    sections: [
      { id: "ddsp", label: "DDSP-SVC", keys: ["ddsp_svc"] },
      { id: "sovits-svc", label: "So-VITS-SVC", keys: ["so_vits_svc"] },
    ],
  },
  {
    id: "visual",
    label: "虚拟身体",
    description: "原 WebUI“虚拟身体”页中的形象驱动与播放器。",
    sections: [
      { id: "live2d", label: "Live2D", keys: ["live2d"] },
      { id: "easy", label: "EasyAIVtuber", keys: ["EasyAIVtuber"] },
    ],
  },
  {
    id: "integral",
    label: "积分",
    description: "签到、礼物、入场及积分查询设置。",
    sections: [
      { id: "integral", label: "积分系统", keys: ["integral"] },
    ],
  },
  {
    id: "analysis",
    label: "数据分析",
    description: "弹幕、积分和礼物数据分析设置。",
    sections: [
      { id: "analysis", label: "数据分析", keys: ["data_analysis"] },
    ],
  },
  {
    id: "page",
    label: "页面配置",
    description: "WebUI 服务、主题、板块显示和账号管理设置。",
    sections: [
      { id: "webui", label: "WebUI 页面配置", keys: ["webui"] },
      { id: "login", label: "账号管理", keys: ["login"] },
    ],
  },
];

const TOP_LEVEL_LABELS: Readonly<Record<string, string>> = {
  "k:agent": "Pi Agent 主配置",
  "k:api_ip": "后端 API 地址",
  "k:api_port": "后端 API 端口",
  "k:platform": "直播平台",
  "k:room_display_id": "直播间号",
  "k:before_prompt": "提示词前缀",
  "k:after_prompt": "提示词后缀",
  "k:comment_template": "弹幕模板",
  "k:reply_template": "回复模板",
  "k:comment_log_type": "弹幕日志类型",
  "k:audio_synthesis_type": "语音合成引擎",
  "k:visual_body": "虚拟身体类型",
  "k:header": "HTTP 请求头",
  "k:bilibili-web": "哔哩哔哩 Web",
  "k:bilibili-platform": "哔哩哔哩开放平台",
  "k:ordinaryroad_barrage_fly": "让弹幕飞",
  "k:twitch": "Twitch",
  "k:play_audio": "音频播放",
  "k:virtual_microphone": "虚拟麦克风",
  "k:filter": "关键词屏蔽",
  "k:speech": "语音队列",
  "k:thanks": "LLM 答谢",
  "k:schedule": "定时任务",
  "k:idle_time_task": "闲时任务",
  "k:search_online": "联网搜索",
  "k:captions": "日志与字幕",
  "k:database": "数据库",
  "k:edge-tts": "Edge TTS",
  "k:vits": "VITS Simple API",
  "k:bert_vits2": "Bert-VITS2",
  "k:openai_tts": "OpenAI TTS",
  "k:gpt_sovits": "GPT-SoVITS",
  "k:azure_tts": "Azure TTS",
  "k:ddsp_svc": "DDSP-SVC",
  "k:so_vits_svc": "So-VITS-SVC",
  "k:live2d": "Live2D",
  "k:EasyAIVtuber": "EasyAIVtuber",
  "k:image_recognition": "专用视觉模型",
  "k:integral": "积分系统",
  "k:data_analysis": "数据分析",
  "k:webui": "WebUI 页面配置",
  "k:login": "账号管理",
};

const CURATED_SEGMENT_LABELS: Readonly<Record<string, string>> = {
  "s:Authorization": "API 授权密钥",
  "s:accent": "口音",
  "s:button_bottom": "底部按钮样式",
  "s:button_bottom_color": "底部按钮颜色",
  "s:button_internal": "内部按钮样式",
  "s:button_internal_color": "内部按钮颜色",
  "s:card": "卡片样式",
  "s:compile": "编译优化",
  "s:cookie": "登录凭据（Cookie）",
  "s:cut_by_sent": "按句切分",
  "s:download_root": "模型下载目录",
  "s:echart": "图表样式",
  "s:fd": "会话标识（fd）",
  "s:http": "HTTP 代理",
  "s:https": "HTTPS 代理",
  "s:instruction_template": "指令模板",
  "s:login_card": "登录卡片样式",
  "s:new": "新版接口参数",
  "s:order": "顺序",
  "s:parallel_infer": "并行推理",
  "s:precision": "计算精度",
  "s:quiet": "静默模式",
  "s:remove_silence": "移除静音",
  "s:rep_pen": "重复惩罚",
  "s:rep_pen_range": "重复惩罚范围",
  "s:rep_pen_slope": "重复惩罚斜率",
  "s:return_fragment": "返回音频分片",
  "s:sdp_ratio": "SDP／DP 混合比",
  "s:socks5": "SOCKS5 代理",
  "s:split_bucket": "分桶切分",
  "s:split_result": "拆分搜索结果",
  "s:streaming": "流式输出",
  "s:streaming_mode": "流式输出模式",
  "s:switch_internal": "内部开关样式",
  "s:tab_panel": "标签面板样式",
  "s:tfs": "尾部自由采样（TFS）",
  "s:tokenizer": "分词器",
  "s:top_a": "Top-A 采样阈值",
  "s:typical": "典型采样阈值",
  "s:ums_api": "账号服务 API 地址",
  "s:url": "请求地址（URL）",
  "s:use_g2p": "使用字音转换（G2P）",
};

const ORIGINAL_PATH_LABELS: Readonly<Record<string, string>> = {
  "p:[\"agent\"]": "Pi Agent 主配置",
  "p:[\"agent\",\"mode\"]": "运行模式",
  "p:[\"agent\",\"provider\"]": "模型供应商",
  "p:[\"agent\",\"model\"]": "模型",
  "p:[\"agent\",\"apiKey\"]": "API 密钥",
  "p:[\"agent\",\"baseUrl\"]": "兼容接口 Base URL",
  "p:[\"agent\",\"systemPrompt\"]": "系统提示词",
  "p:[\"agent\",\"maxTokens\"]": "最大输出 Token",
  "p:[\"agent\",\"contextWindow\"]": "上下文窗口",
  "p:[\"agent\",\"maxSessions\"]": "最大会话数",
  "p:[\"agent\",\"thinkingLevel\"]": "思考等级",
  "p:[\"agent\",\"reasoning\"]": "推理",
  "p:[\"agent\",\"input\"]": "视觉",
  "p:[\"agent\",\"tools\"]": "工具",
  "p:[\"agent\",\"headers\"]": "附加请求头",
  "p:[\"agent\",\"samplingParams\"]": "附加采样参数",
  "p:[\"platform\"]": "平台",
  "p:[\"room_display_id\"]": "直播间号",
  "p:[\"visual_body\"]": "虚拟身体",
  "p:[\"audio_synthesis_type\"]": "语音合成",
  "p:[\"before_prompt\"]": "提示词前缀",
  "p:[\"after_prompt\"]": "提示词后缀",
  "p:[\"comment_template\",\"enable\"]": "启用弹幕模板",
  "p:[\"comment_template\",\"copywriting\"]": "弹幕模板",
  "p:[\"reply_template\",\"enable\"]": "启用回复模板",
  "p:[\"reply_template\",\"username_max_len\"]": "回复用户名的最大长度",
  "p:[\"reply_template\",\"copywriting\"]": "回复模板",
  "p:[\"bilibili-web\",\"room_id\"]": "B站直播间号",
  "p:[\"bilibili-web\",\"uid\"]": "B站用户 ID",
  "p:[\"bilibili-web\",\"sessdata\"]": "SESSDATA",
  "p:[\"bilibili-web\",\"cookie\"]": "完整 Cookie",
  "p:[\"bilibili-platform\",\"ACCESS_KEY_ID\"]": "Access Key ID",
  "p:[\"bilibili-platform\",\"ACCESS_KEY_SECRET\"]": "Access Key Secret",
  "p:[\"bilibili-platform\",\"APP_ID\"]": "项目 ID",
  "p:[\"bilibili-platform\",\"ROOM_OWNER_AUTH_CODE\"]": "主播身份码",
  "p:[\"ordinaryroad_barrage_fly\",\"ws_ip_port\"]": "WebSocket地址",
  "p:[\"ordinaryroad_barrage_fly\",\"taskIds\"]": "任务ID",
  "p:[\"twitch\",\"user\"]": "用户名",
  "p:[\"twitch\",\"proxy_server\"]": "HTTP代理IP地址",
  "p:[\"twitch\",\"proxy_port\"]": "HTTP代理端口",
  "p:[\"play_audio\",\"enable\"]": "启用",
  "p:[\"play_audio\",\"text_split_enable\"]": "启用文本切分",
  "p:[\"play_audio\",\"info_to_callback\"]": "音频信息回传给内部接口",
  "p:[\"play_audio\",\"interval_num_min\"]": "间隔时间重复次数最小值",
  "p:[\"play_audio\",\"interval_num_max\"]": "间隔时间重复次数最大值",
  "p:[\"play_audio\",\"normal_interval_min\"]": "普通音频播放间隔最小值",
  "p:[\"play_audio\",\"normal_interval_max\"]": "普通音频播放间隔最大值",
  "p:[\"play_audio\",\"out_path\"]": "音频输出路径",
  "p:[\"play_audio\",\"player\"]": "音频播放器",
  "p:[\"virtual_microphone\",\"enable\"]": "启用虚拟麦克风",
  "p:[\"virtual_microphone\",\"device\"]": "虚拟麦克风播放设备",
  "p:[\"virtual_microphone\",\"executable\"]": "虚拟麦克风播放器",
  "p:[\"virtual_microphone\",\"args\"]": "虚拟麦克风播放器参数",
  "p:[\"filter\",\"badwords\",\"enable\"]": "关键词屏蔽",
  "p:[\"filter\",\"badwords\",\"discard\"]": "命中后丢弃消息",
  "p:[\"filter\",\"badwords\",\"path\"]": "关键词词库路径",
  "p:[\"filter\",\"badwords\",\"replace\"]": "替换文本",
  "p:[\"speech\",\"queue_capacity\"]": "语音队列容量",
  "p:[\"speech\",\"queue_start_threshold\"]": "队列启动播放阈值",
  "p:[\"speech\",\"priority_mapping\"]": "语音播放优先级",
  "p:[\"speech\",\"priority_mapping\",\"idle_time_task\"]": "闲时任务 优先级",
  "p:[\"speech\",\"priority_mapping\",\"image_recognition_schedule\"]": "图像识别 优先级",
  "p:[\"speech\",\"priority_mapping\",\"comment\"]": "弹幕回复 优先级",
  "p:[\"speech\",\"priority_mapping\",\"entrance\"]": "入场欢迎 优先级",
  "p:[\"speech\",\"priority_mapping\",\"gift\"]": "礼物答谢 优先级",
  "p:[\"speech\",\"priority_mapping\",\"follow\"]": "关注答谢 优先级",
  "p:[\"speech\",\"priority_mapping\",\"talk\"]": "聊天（语音输入） 优先级",
  "p:[\"speech\",\"priority_mapping\",\"reread\"]": "复读 优先级",
  "p:[\"speech\",\"priority_mapping\",\"integral\"]": "积分 优先级",
  "p:[\"speech\",\"priority_mapping\",\"reread_top_priority\"]": "最高优先级复读 优先级",
  "p:[\"speech\",\"priority_mapping\",\"schedule\"]": "定时任务 优先级",
  "p:[\"thanks\",\"entrance_enable\"]": "入场时触发 LLM 回复",
  "p:[\"thanks\",\"gift_enable\"]": "收到礼物时触发 LLM 回复",
  "p:[\"thanks\",\"follow_enable\"]": "关注时触发 LLM 回复",
  "p:[\"idle_time_task\",\"enable\"]": "闲时触发 LLM 回复",
  "p:[\"idle_time_task\",\"type\"]": "机制类型",
  "p:[\"idle_time_task\",\"min_msg_queue_len_to_trigger\"]": "待合成消息队列个数小于此值时触发",
  "p:[\"idle_time_task\",\"min_audio_queue_len_to_trigger\"]": "待播放音频队列个数小于此值时触发",
  "p:[\"idle_time_task\",\"idle_time_min\"]": "最小闲时时间",
  "p:[\"idle_time_task\",\"idle_time_max\"]": "最大闲时时间",
  "p:[\"idle_time_task\",\"wait_play_audio_num_threshold\"]": "等待播放音频数量阈值",
  "p:[\"idle_time_task\",\"idle_time_reduce_to\"]": "闲时计时减小到",
  "p:[\"idle_time_task\",\"copywriting\"]": "文案提示",
  "p:[\"idle_time_task\",\"copywriting\",\"enable\"]": "启用文案提示",
  "p:[\"idle_time_task\",\"copywriting\",\"random\"]": "随机文案提示",
  "p:[\"idle_time_task\",\"copywriting\",\"copy\"]": "文案提示列表",
  "p:[\"idle_time_task\",\"comment\"]": "话题提示",
  "p:[\"idle_time_task\",\"comment\",\"enable\"]": "启用话题提示",
  "p:[\"idle_time_task\",\"comment\",\"random\"]": "随机话题提示",
  "p:[\"idle_time_task\",\"comment\",\"copy\"]": "话题提示列表",
  "p:[\"search_online\",\"enable\"]": "注册网页搜索工具",
  "p:[\"search_online\",\"provider\"]": "搜索 API 服务商",
  "p:[\"search_online\",\"api_key\"]": "API Key（启用时必填）",
  "p:[\"search_online\",\"endpoint\"]": "API 接口地址（可选）",
  "p:[\"search_online\",\"model\"]": "搜索模型（可选）",
  "p:[\"search_online\",\"count\"]": "最大来源数",
  "p:[\"search_online\",\"http_proxy\"]": "HTTP代理地址",
  "p:[\"search_online\",\"https_proxy\"]": "HTTPS代理地址",
  "p:[\"captions\",\"enable\"]": "启用",
  "p:[\"comment_log_type\"]": "弹幕日志类型",
  "p:[\"captions\",\"file_path\"]": "字幕日志路径",
  "p:[\"captions\",\"raw_file_path\"]": "原文字幕日志路径",
  "p:[\"database\",\"comment_enable\"]": "弹幕日志",
  "p:[\"database\",\"entrance_enable\"]": "入场日志",
  "p:[\"database\",\"gift_enable\"]": "礼物日志",
  "p:[\"database\",\"path\"]": "数据库路径",
  "p:[\"edge-tts\",\"voice\"]": "说话人",
  "p:[\"edge-tts\",\"rate\"]": "语速增益",
  "p:[\"edge-tts\",\"volume\"]": "音量增益",
  "p:[\"edge-tts\",\"proxy\"]": "HTTP代理地址",
  "p:[\"vits\",\"type\"]": "类型",
  "p:[\"vits\",\"config_path\"]": "配置文件路径",
  "p:[\"vits\",\"api_ip_port\"]": "API地址",
  "p:[\"vits\",\"id\"]": "说话人ID",
  "p:[\"vits\",\"lang\"]": "语言",
  "p:[\"vits\",\"length\"]": "语音长度",
  "p:[\"vits\",\"noise\"]": "噪声",
  "p:[\"vits\",\"noisew\"]": "噪声偏差",
  "p:[\"vits\",\"max\"]": "分段阈值",
  "p:[\"vits\",\"format\"]": "音频格式",
  "p:[\"vits\",\"sdp_radio\"]": "SDP/DP混合比",
  "p:[\"vits\",\"gpt_sovits\",\"id\"]": "历史保留：说话人ID",
  "p:[\"vits\",\"gpt_sovits\",\"lang\"]": "历史保留：语言",
  "p:[\"vits\",\"gpt_sovits\",\"format\"]": "历史保留：音频格式",
  "p:[\"vits\",\"gpt_sovits\",\"reference_audio\"]": "历史保留：参考音频路径",
  "p:[\"vits\",\"gpt_sovits\",\"prompt_text\"]": "历史保留：参考音频文本内容",
  "p:[\"vits\",\"gpt_sovits\",\"prompt_lang\"]": "历史保留：参考音频语言",
  "p:[\"bert_vits2\",\"type\"]": "类型",
  "p:[\"bert_vits2\",\"api_ip_port\"]": "API地址",
  "p:[\"bert_vits2\",\"model_id\"]": "模型ID",
  "p:[\"bert_vits2\",\"speaker_name\"]": "说话人名称",
  "p:[\"bert_vits2\",\"speaker_id\"]": "说话人ID",
  "p:[\"bert_vits2\",\"language\"]": "语言",
  "p:[\"bert_vits2\",\"length\"]": "语音长度",
  "p:[\"bert_vits2\",\"noise\"]": "噪声",
  "p:[\"bert_vits2\",\"noisew\"]": "噪声偏差",
  "p:[\"bert_vits2\",\"sdp_radio\"]": "SDP/DP混合比",
  "p:[\"bert_vits2\",\"style_text\"]": "风格文本",
  "p:[\"bert_vits2\",\"style_weight\"]": "风格权重",
  "p:[\"bert_vits2\",\"auto_translate\"]": "自动翻译",
  "p:[\"bert_vits2\",\"auto_split\"]": "自动切分",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"api_ip_port\"]": "历史保留：API地址",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"speaker\"]": "历史保留：说话人名称",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"language\"]": "历史保留：语言",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"length_scale\"]": "历史保留：语音长度",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"noise_scale\"]": "历史保留：噪声",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"noise_scale_w\"]": "历史保留：噪声偏差",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"sdp_radio\"]": "历史保留：SDP/DP混合比",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"style_text\"]": "历史保留：风格文本",
  "p:[\"bert_vits2\",\"刘悦-中文特化API\",\"style_weight\"]": "历史保留：风格权重",
  "p:[\"openai_tts\",\"type\"]": "类型",
  "p:[\"openai_tts\",\"api_ip_port\"]": "API地址",
  "p:[\"openai_tts\",\"model\"]": "模型",
  "p:[\"openai_tts\",\"voice\"]": "说话人",
  "p:[\"gpt_sovits\",\"type\"]": "API类型",
  "p:[\"gpt_sovits\",\"gradio_ip_port\"]": "Gradio API地址",
  "p:[\"gpt_sovits\",\"api_ip_port\"]": "API地址（http）",
  "p:[\"gpt_sovits\",\"gpt_model_path\"]": "历史保留：GPT模型路径",
  "p:[\"gpt_sovits\",\"sovits_model_path\"]": "历史保留：SOVITS模型路径",
  "p:[\"gpt_sovits\",\"ref_audio_path\"]": "参考音频路径",
  "p:[\"gpt_sovits\",\"prompt_text\"]": "参考音频的文本",
  "p:[\"gpt_sovits\",\"prompt_language\"]": "参考音频的语种",
  "p:[\"gpt_sovits\",\"language\"]": "需要合成的语种",
  "p:[\"gpt_sovits\",\"cut\"]": "语句切分",
  "p:[\"gpt_sovits\",\"api_0322\",\"ref_audio_path\"]": "参考音频路径",
  "p:[\"gpt_sovits\",\"api_0322\",\"prompt_text\"]": "参考音频的文本",
  "p:[\"gpt_sovits\",\"api_0322\",\"prompt_lang\"]": "参考音频的语种",
  "p:[\"gpt_sovits\",\"api_0322\",\"text_lang\"]": "需要合成的语种",
  "p:[\"gpt_sovits\",\"api_0322\",\"text_split_method\"]": "语句切分",
  "p:[\"gpt_sovits\",\"api_0322\",\"fragment_interval\"]": "分段间隔(秒)",
  "p:[\"gpt_sovits\",\"api_0706\",\"refer_wav_path\"]": "参考音频路径",
  "p:[\"gpt_sovits\",\"api_0706\",\"prompt_text\"]": "参考音频的文本",
  "p:[\"gpt_sovits\",\"api_0706\",\"prompt_language\"]": "参考音频的语种",
  "p:[\"gpt_sovits\",\"api_0706\",\"text_language\"]": "需要合成的语种",
  "p:[\"gpt_sovits\",\"api_0706\",\"cut_punc\"]": "文本切分",
  "p:[\"gpt_sovits\",\"v2_api_0821\",\"ref_audio_path\"]": "参考音频路径",
  "p:[\"gpt_sovits\",\"v2_api_0821\",\"prompt_text\"]": "参考音频的文本",
  "p:[\"gpt_sovits\",\"v2_api_0821\",\"prompt_lang\"]": "参考音频的语种",
  "p:[\"gpt_sovits\",\"v2_api_0821\",\"text_lang\"]": "需要合成的语种",
  "p:[\"gpt_sovits\",\"v2_api_0821\",\"text_split_method\"]": "语句切分",
  "p:[\"gpt_sovits\",\"v2_api_0821\",\"fragment_interval\"]": "分段间隔(秒)",
  "p:[\"gpt_sovits\",\"webtts\",\"version\"]": "版本",
  "p:[\"gpt_sovits\",\"webtts\",\"api_ip_port\"]": "API地址",
  "p:[\"gpt_sovits\",\"webtts\",\"spk\"]": "音色",
  "p:[\"gpt_sovits\",\"webtts\",\"lang\"]": "语言",
  "p:[\"gpt_sovits\",\"webtts\",\"speed\"]": "语速",
  "p:[\"gpt_sovits\",\"webtts\",\"emotion\"]": "情感",
  "p:[\"azure_tts\",\"subscription_key\"]": "密钥",
  "p:[\"azure_tts\",\"region\"]": "区域",
  "p:[\"azure_tts\",\"voice_name\"]": "说话人名",
  "p:[\"ddsp_svc\",\"enable\"]": "启用",
  "p:[\"ddsp_svc\",\"config_path\"]": "配置文件路径",
  "p:[\"ddsp_svc\",\"api_ip_port\"]": "API地址",
  "p:[\"ddsp_svc\",\"fSafePrefixPadLength\"]": "安全前缀填充长度",
  "p:[\"ddsp_svc\",\"fPitchChange\"]": "变调",
  "p:[\"ddsp_svc\",\"sSpeakId\"]": "说话人ID",
  "p:[\"ddsp_svc\",\"sampleRate\"]": "采样率",
  "p:[\"so_vits_svc\",\"enable\"]": "启用",
  "p:[\"so_vits_svc\",\"config_path\"]": "配置文件路径",
  "p:[\"so_vits_svc\",\"api_ip_port\"]": "API地址",
  "p:[\"so_vits_svc\",\"spk\"]": "说话人",
  "p:[\"so_vits_svc\",\"tran\"]": "音调",
  "p:[\"so_vits_svc\",\"wav_format\"]": "输出音频格式",
  "p:[\"live2d\",\"enable\"]": "启用",
  "p:[\"live2d\",\"port\"]": "端口",
  "p:[\"live2d\",\"name\"]": "模型名",
  "p:[\"live2d\",\"camera\"]": "OBS 虚拟摄像头",
  "p:[\"live2d\",\"camera\",\"obs_websocket_url\"]": "OBS WebSocket 地址",
  "p:[\"live2d\",\"camera\",\"password\"]": "OBS WebSocket 密码",
  "p:[\"live2d\",\"camera\",\"width\"]": "输出宽度",
  "p:[\"live2d\",\"camera\",\"height\"]": "输出高度",
  "p:[\"live2d\",\"camera\",\"fps\"]": "输出帧率",
  "p:[\"live2d\",\"camera\",\"auto_start\"]": "运行时自动启动虚拟摄像头",
  "p:[\"EasyAIVtuber\",\"api_ip_port\"]": "API地址",
  "p:[\"integral\",\"enable\"]": "启用",
  "p:[\"integral\",\"sign\",\"enable\"]": "启用",
  "p:[\"integral\",\"sign\",\"get_integral\"]": "获得积分数",
  "p:[\"integral\",\"sign\",\"cmd\"]": "命令",
  "p:[\"integral\",\"gift\",\"enable\"]": "启用",
  "p:[\"integral\",\"gift\",\"get_integral_proportion\"]": "获得积分比例",
  "p:[\"integral\",\"entrance\",\"enable\"]": "启用",
  "p:[\"integral\",\"entrance\",\"get_integral\"]": "获得积分数",
  "p:[\"integral\",\"crud\",\"query\",\"enable\"]": "启用",
  "p:[\"integral\",\"crud\",\"query\",\"cmd\"]": "命令",
  "p:[\"integral\",\"crud\",\"query\",\"copywriting\"]": "文案",
  "p:[\"image_recognition\",\"enable\"]": "启用专用视觉模型",
  "p:[\"image_recognition\",\"provider\"]": "视觉模型供应商",
  "p:[\"image_recognition\",\"model\"]": "视觉模型",
  "p:[\"image_recognition\",\"apiKey\"]": "视觉模型 API 密钥",
  "p:[\"image_recognition\",\"baseUrl\"]": "视觉模型 Base URL",
  "p:[\"image_recognition\",\"systemPrompt\"]": "视觉转述系统提示词",
  "p:[\"image_recognition\",\"prompt\"]": "图片转述指令",
  "p:[\"image_recognition\",\"maxTokens\"]": "视觉模型最大输出",
  "p:[\"image_recognition\",\"contextWindow\"]": "视觉模型上下文窗口",
  "p:[\"image_recognition\",\"maxSessions\"]": "视觉模型最大会话数",
  "p:[\"image_recognition\",\"thinkingLevel\"]": "视觉模型思考等级",
  "p:[\"image_recognition\",\"reasoning\"]": "视觉模型推理",
  "p:[\"image_recognition\",\"headers\"]": "视觉模型附加请求头",
  "p:[\"image_recognition\",\"samplingParams\"]": "视觉模型附加采样参数",
  "p:[\"data_analysis\",\"comment_word_cloud\",\"top_num\"]": "前N个关键词",
  "p:[\"data_analysis\",\"integral\",\"top_num\"]": "Top N个数据",
  "p:[\"data_analysis\",\"gift\",\"top_num\"]": "Top N个数据",
  "p:[\"webui\",\"title\"]": "历史保留：标题",
  "p:[\"webui\",\"ip\"]": "IP地址",
  "p:[\"webui\",\"port\"]": "端口",
  "p:[\"webui\",\"auto_run\"]": "历史保留：自动运行",
  "p:[\"webui\",\"local_dir_to_endpoint\",\"enable\"]": "历史保留：启用",
  "p:[\"webui\",\"theme\",\"choose\"]": "历史保留：主题",
  "p:[\"webui\",\"show_card\",\"common_config\",\"filter\"]": "历史保留：过滤",
  "p:[\"webui\",\"show_card\",\"common_config\",\"thanks\"]": "历史保留：LLM 答谢",
  "p:[\"webui\",\"show_card\",\"common_config\",\"log\"]": "历史保留：日志",
  "p:[\"webui\",\"show_card\",\"common_config\",\"schedule\"]": "历史保留：定时任务",
  "p:[\"webui\",\"show_card\",\"common_config\",\"idle_time_task\"]": "历史保留：闲时任务",
  "p:[\"webui\",\"show_card\",\"common_config\",\"database\"]": "历史保留：数据库",
  "p:[\"webui\",\"show_card\",\"common_config\",\"play_audio\"]": "历史保留：音频播放",
  "p:[\"webui\",\"show_card\",\"common_config\",\"virtual_microphone\"]": "历史保留：虚拟麦克风",
  "p:[\"login\",\"enable\"]": "登录功能",
  "p:[\"login\",\"username\"]": "用户名",
  "p:[\"login\",\"password\"]": "密码",
};

const ORIGINAL_SEGMENT_LABELS: Readonly<Record<string, string>> = {
  "s:APP_ID": "项目ID",
  "s:ROOM_OWNER_AUTH_CODE": "身份码",
  "s:access_token": "密钥",
  "s:after_prompt": "提示词后缀",
  "s:api": "API地址",
  "s:api_ip_port": "API地址",
  "s:api_key": "API密钥",
  "s:api_secret": "智能体API Secret",
  "s:app_id": "应用ID",
  "s:app_key": "应用ID",
  "s:app_secret": "密钥",
  "s:assistant_id": "助手ID",
  "s:audio_seed_input": "声音种子",
  "s:audio_synthesis_type": "语音合成",
  "s:auto_run": "自动运行",
  "s:auto_split": "自动切分",
  "s:before_prompt": "提示词前缀",
  "s:body": "请求体",
  "s:body_type": "请求体类型",
  "s:bot_info": "角色信息",
  "s:bot_name": "角色名称",
  "s:break_clone": "减弱风格影响",
  "s:chain_type": "链类型",
  "s:character": "说话人",
  "s:character_id": "角色ID",
  "s:chat_mode": "聊天模式",
  "s:choose": "主题",
  "s:chunk_overlap": "块重叠",
  "s:chunk_size": "块大小",
  "s:ckpt_path": "模型路径",
  "s:cmd": "命令",
  "s:comment_log_type": "弹幕日志类型",
  "s:config_path": "配置文件路径",
  "s:cookie_path": "cookie路径",
  "s:copy": "文案列表",
  "s:copywriting": "文案",
  "s:count": "检索的文章数",
  "s:custom_params": "工作流自定义参数（JSON）",
  "s:cut": "语句切分",
  "s:cut_punc": "文本切分",
  "s:data_path": "数据文件路径",
  "s:database": "数据库",
  "s:db_path": "数据库路径",
  "s:emotion": "情感",
  "s:enable": "启用",
  "s:enable_ref_audio": "启用参考音频",
  "s:enable_ref_audio_update": "参考音频过期自动更新",
  "s:enable_search": "联网搜索",
  "s:end_of_sentence_probability": "句末概率",
  "s:engine": "搜索引擎",
  "s:engine_id": "引擎ID",
  "s:fPitchChange": "变调",
  "s:fSafePrefixPadLength": "安全前缀填充长度",
  "s:file_path": "音频存储路径",
  "s:filter": "过滤",
  "s:flash": "加速模式生成",
  "s:follow": "关注答谢 优先级",
  "s:follow_enable": "启用关注答谢",
  "s:format": "音频格式",
  "s:fragment_interval": "分段间隔(秒)",
  "s:frequency_penalty": "频率惩罚",
  "s:generation_temperature": "生成温度",
  "s:get_integral": "获得积分数",
  "s:get_integral_proportion": "获得积分比例",
  "s:gpt_model_path": "GPT模型路径",
  "s:gradio_ip_port": "Gradio API地址",
  "s:headers": "请求头",
  "s:history_enable": "上下文记忆",
  "s:history_max_len": "最大记忆长度",
  "s:http_proxy": "HTTP代理地址",
  "s:https_proxy": "HTTPS代理地址",
  "s:id": "说话人ID",
  "s:idle_time_max": "最大闲时时间",
  "s:idle_time_min": "最小闲时时间",
  "s:idle_time_reduce_to": "闲时计时减小到",
  "s:idle_time_task": "闲时任务",
  "s:info_to_callback": "音频信息回传给内部接口",
  "s:instruct_text": "instruct文本",
  "s:integral": "积分 优先级",
  "s:interval_num_max": "间隔时间重复次数最大值",
  "s:interval_num_min": "间隔时间重复次数最小值",
  "s:ip": "IP地址",
  "s:kb_ids": "知识库ID",
  "s:keyword_enable": "关键词触发",
  "s:keywords": "打断关键词",
  "s:knowledge_base_id": "知识库名称",
  "s:knowledge_base_name": "知识库名",
  "s:lang": "语言",
  "s:language": "语言",
  "s:length": "语音长度",
  "s:length_scale": "语音长度",
  "s:local_max_query": "最大查询数据库次数",
  "s:local_vector_embedding_model": "模型",
  "s:log": "日志",
  "s:login_type": "登录方式",
  "s:sessdata": "SESSDATA",
  "s:max": "分段阈值",
  "s:max_char_len": "最大字符数",
  "s:max_len": "最大单词数",
  "s:max_length": "最大长度限制",
  "s:max_new_tokens": "每批最大令牌数",
  "s:max_output_tokens": "最大输出token数",
  "s:max_tokens": "最大token数",
  "s:media_type": "音频格式",
  "s:method": "API类型",
  "s:min_audio_queue_len_to_trigger": "待播放音频队列个数小于此值时触发",
  "s:min_msg_queue_len_to_trigger": "待合成消息队列个数小于此值时触发",
  "s:mode": "类型",
  "s:mode_checkbox_group": "推理模式",
  "s:model": "模型",
  "s:model_id": "模型ID",
  "s:model_name": "LLM模型",
  "s:name": "模型名",
  "s:noise": "噪声",
  "s:noise_scale": "噪声",
  "s:noise_scale_w": "噪声偏差",
  "s:noisew": "噪声偏差",
  "s:normal_interval_max": "普通音频播放间隔最大值",
  "s:normal_interval_min": "普通音频播放间隔最小值",
  "s:out_path": "音频输出路径",
  "s:password": "密码",
  "s:path": "数据库路径",
  "s:penalty_score": "惩罚得分",
  "s:pitch": "音调",
  "s:platform": "平台",
  "s:play_audio": "音频播放",
  "s:play_interval": "文案播放间隔",
  "s:player": "音频播放器",
  "s:port": "端口",
  "s:presence_penalty": "存在惩罚",
  "s:preset": "预设",
  "s:probability_optimization": "概率优选",
  "s:prompt": "携带的提示词",
  "s:promptId": "角色风格 ID",
  "s:prompt_audio": "prompt音频路径",
  "s:prompt_lang": "参考音频的语种",
  "s:prompt_language": "参考音频的语种",
  "s:prompt_name": "Prompt模板",
  "s:prompt_text": "参考音频的文本",
  "s:prompt_wav_upload": "prompt音频路径",
  "s:provider": "供应商",
  "s:proxies": "代理",
  "s:proxy": "HTTP代理地址",
  "s:proxy_port": "HTTP代理端口",
  "s:proxy_server": "HTTP代理IP地址",
  "s:question_prompt": "问题总结提示词",
  "s:quick_generation": "快速生成",
  "s:random": "随机文案",
  "s:randomness": "多样性",
  "s:rate": "语速增益",
  "s:raw_file_path": "原文字幕日志路径",
  "s:ref_audio_orig": "参考音频路径",
  "s:ref_audio_path": "参考音频路径",
  "s:ref_text": "参考文本",
  "s:refer_wav_path": "参考音频路径",
  "s:reference_audio": "参考音频路径",
  "s:reference_text": "参考文本",
  "s:region": "区域",
  "s:remove_useless": "删除无用字符",
  "s:repetition_penalty": "重复惩罚",
  "s:replace": "违禁词替换",
  "s:request_parameters": "请求参数",
  "s:reread": "复读 优先级",
  "s:reread_top_priority": "最高优先级复读 优先级",
  "s:role_name": "固定角色名称",
  "s:room_display_id": "直播间号",
  "s:sSpeakId": "说话人ID",
  "s:sampleRate": "采样率",
  "s:save_path": "图片保存路径",
  "s:schedule": "定时任务",
  "s:score_threshold": "知识匹配分数阈值",
  "s:search_engine_name": "搜索引擎",
  "s:seed": "随机种子",
  "s:separator": "分隔符",
  "s:sft_dropdown": "预训练音色",
  "s:show_token_cost": "显示成本",
  "s:sovits_model_path": "SOVITS模型路径",
  "s:speaker": "说话人",
  "s:speaker_id": "说话人ID",
  "s:speaker_name": "说话人名称",
  "s:speed": "语速",
  "s:speed_max": "速度上限",
  "s:speed_min": "速度下限",
  "s:spk": "说话人",
  "s:stability_boost": "稳定性过滤",
  "s:stream": "流式输出",
  "s:style_text": "风格文本",
  "s:style_weight": "风格权重",
  "s:subscription_key": "密钥",
  "s:talk": "聊天（语音输入） 优先级",
  "s:taskIds": "任务ID",
  "s:temperature": "温度",
  "s:text_lang": "需要合成的语种",
  "s:text_language": "需要合成的语种",
  "s:text_split_enable": "启用文本切分",
  "s:text_split_method": "语句切分",
  "s:thanks": "LLM 答谢",
  "s:title": "标题",
  "s:top_k": "匹配搜索结果条数",
  "s:top_num": "Top N个数据",
  "s:top_p": "前p个选择",
  "s:tran": "音调",
  "s:type": "类型",
  "s:use_hf": "使用HF默认模型",
  "s:use_proxy": "启用代理",
  "s:user": "用户名",
  "s:user_id": "用户ID",
  "s:user_info": "用户信息",
  "s:username": "账号",
  "s:username_max_len": "用户名最大长度",
  "s:version": "版本",
  "s:visual_body": "虚拟身体",
  "s:voice": "说话人",
  "s:voiceId": "角色ID",
  "s:voice_change": "变声",
  "s:voice_name": "说话人名",
  "s:volume": "音量",
  "s:wait_play_audio_num_threshold": "等待播放音频数量阈值",
  "s:wav_format": "输出音频格式",
  "s:waveform_temperature": "波形温度",
  "s:workspace_slug": "工作区slug",
  "s:ws_ip_port": "WebSocket地址",
};

const TOKEN_LABELS: Readonly<Record<string, string>> = {
  "t:api": "API",
  "t:app": "应用",
  "t:audio": "音频",
  "t:auto": "自动",
  "t:background": "背景",
  "t:base": "基础",
  "t:batch": "批次",
  "t:body": "身体",
  "t:chat": "对话",
  "t:check": "检查",
  "t:clean": "清理",
  "t:client": "客户端",
  "t:cmd": "命令",
  "t:comment": "弹幕",
  "t:config": "配置",
  "t:copywriting": "文案",
  "t:count": "数量",
  "t:database": "数据库",
  "t:delay": "延迟",
  "t:device": "设备",
  "t:directory": "目录",
  "t:duration": "时长",
  "t:enable": "启用",
  "t:end": "结束",
  "t:error": "错误",
  "t:file": "文件",
  "t:filter": "过滤",
  "t:format": "格式",
  "t:frequency": "频率",
  "t:gift": "礼物",
  "t:group": "分组",
  "t:header": "请求头",
  "t:history": "上下文",
  "t:host": "主机",
  "t:http": "HTTP",
  "t:https": "HTTPS",
  "t:id": "ID",
  "t:image": "图像",
  "t:input": "输入",
  "t:interval": "间隔",
  "t:ip": "IP",
  "t:key": "密钥",
  "t:lang": "语言",
  "t:language": "语言",
  "t:length": "长度",
  "t:level": "级别",
  "t:list": "列表",
  "t:local": "本地",
  "t:log": "日志",
  "t:max": "最大",
  "t:message": "消息",
  "t:min": "最小",
  "t:mode": "模式",
  "t:model": "模型",
  "t:name": "名称",
  "t:num": "数量",
  "t:output": "输出",
  "t:password": "密码",
  "t:path": "路径",
  "t:player": "播放器",
  "t:port": "端口",
  "t:prefix": "前缀",
  "t:prompt": "提示词",
  "t:proxy": "代理",
  "t:random": "随机",
  "t:rate": "速率",
  "t:reply": "回复",
  "t:request": "请求",
  "t:response": "响应",
  "t:room": "直播间",
  "t:save": "保存",
  "t:secret": "密钥",
  "t:server": "服务端",
  "t:size": "大小",
  "t:speed": "速度",
  "t:start": "开始",
  "t:stream": "流式",
  "t:suffix": "后缀",
  "t:task": "任务",
  "t:text": "文本",
  "t:timeout": "超时",
  "t:token": "令牌",
  "t:type": "类型",
  "t:url": "URL",
  "t:user": "用户",
  "t:username": "用户名",
  "t:value": "值",
  "t:version": "版本",
  "t:voice": "声音",
  "t:web": "Web",
  "t:websocket": "WebSocket",
  "t:width": "宽度",
  "t:window": "窗口",
  "t:ws": "WebSocket",
};

export function settingsPathOptions(
  path: readonly string[],
  config?: Readonly<Record<string, unknown>>,
): readonly SettingsChoiceOption[] | undefined {
  const configured = SETTINGS_PATH_OPTIONS[JSON.stringify(path)];
  if (configured !== undefined) return configured;
  if (
    path.length !== 3
    || path[0] !== "webui"
    || path[1] !== "theme"
    || path[2] !== "choose"
  ) {
    return undefined;
  }
  const webui = config?.["webui"];
  if (webui === null || typeof webui !== "object" || Array.isArray(webui)) {
    return undefined;
  }
  const theme = (webui as Readonly<Record<string, unknown>>)["theme"];
  if (theme === null || typeof theme !== "object" || Array.isArray(theme)) {
    return undefined;
  }
  const list = (theme as Readonly<Record<string, unknown>>)["list"];
  if (list === null || typeof list !== "object" || Array.isArray(list)) {
    return undefined;
  }
  const names = Object.keys(list);
  return names.length === 0
    ? undefined
    : names.map((value) => ({ value, label: value }));
}

export function categorizeSettingsKeys(keys: readonly string[]): SettingsCatalogCategoryGroup[] {
  const remaining = new Set(keys);
  const groups: SettingsCatalogCategoryGroup[] = [];
  for (const category of SETTINGS_CATALOG) {
    const sections: SettingsCatalogSectionGroup[] = [];
    for (const section of category.sections) {
      const presentKeys = section.keys.filter((key) => remaining.delete(key));
      if (presentKeys.length > 0) sections.push({ ...section, keys: presentKeys });
    }
    if (sections.length > 0) groups.push({ ...category, sections });
  }
  if (remaining.size > 0) {
    groups.push({
      id: "other",
      label: "其他配置",
      description: "当前版本新增或原 WebUI 未覆盖的配置，仍按原始 JSON 路径完整保留。",
      sections: [...remaining].map((key) => ({ id: `other-${key}`, label: settingsTopLevelLabel(key), keys: [key] })),
    });
  }
  return groups;
}

export function settingsTopLevelLabel(key: string): string {
  return TOP_LEVEL_LABELS[`k:${key}`] ?? humanizeSettingsKey(key);
}

export function settingsPathLabel(path: readonly string[]): string {
  if (path.length === 0) return "配置";
  if (path[0] === "schedule" && path.length >= 3) {
    if (path[2] === "prompts" && path.length === 4) return `提示词 ${Number(path[3]) + 1}`;
    switch (path[path.length - 1]) {
      case "name": return "任务名称";
      case "enable": return "启用任务";
      case "run_on_start": return "启动时立即执行";
      case "mode": return "执行间隔";
      case "every": return "每隔";
      case "min": return "最短间隔";
      case "max": return "最长间隔";
      case "unit": return "时间单位";
    }
  }
  const exact = ORIGINAL_PATH_LABELS[`p:${JSON.stringify(path)}`];
  if (exact !== undefined) return exact;
  if (path.length === 1) return settingsTopLevelLabel(path[0] as string);
  const key = path[path.length - 1] as string;
  return CURATED_SEGMENT_LABELS[`s:${key}`]
    ?? ORIGINAL_SEGMENT_LABELS[`s:${key}`]
    ?? TOP_LEVEL_LABELS[`k:${key}`]
    ?? humanizeSettingsKey(key);
}

export function settingsPathSearchTerms(path: readonly string[]): string {
  return path.map((_, index) => settingsPathLabel(path.slice(0, index + 1))).join(" ");
}

function humanizeSettingsKey(key: string): string {
  if (/\p{Script=Han}/u.test(key)) return key;
  const normalized = key.replace(/([a-z\d])([A-Z])/g, "$1_$2").replace(/[^A-Za-z\d]+/g, "_");
  const tokens = normalized.split("_").filter((token) => token !== "");
  if (tokens.length === 0) return key;
  return tokens.map((token) => TOKEN_LABELS[`t:${token.toLowerCase()}`] ?? token).join(" ");
}
